// GENERATED — do not edit by hand.
// Source: /root/.openclaw/workspace/msga-replay/swingmate_v3/phase_c_runs/phase_h_final_20260703_portfolio_STAGED.json
// Regenerated by msga-replay/swingmate_v3/gen_basket_constant.py on every publisher cycle.
//
// This list gates the Live Trading pair chips and the symbols polled for open positions. When it
// was maintained by hand it drifted to 19 assets against a 29-asset basket — still listing HYPE,
// which is no longer traded, and missing eleven coins that are. A coin missing from here is a
// position the customer cannot see.
export const PHASE_H_BASKET_GENERATED = [
  'AAVE',
  'ADA',
  'ATOM',
  'AVAX',
  'BCH',
  'BNB',
  'BTC',
  'DOGE',
  'ETC',
  'ETH',
  'FIL',
  'GRAM',
  'HBAR',
  'LINK',
  'LTC',
  'NEAR',
  'ONDO',
  'OP',
  'PEPE',
  'RUNE',
  'SEI',
  'SOL',
  'SUI',
  'TAO',
  'TRX',
  'WLD',
  'XLM',
  'XRP',
  'ZEC',
] as const
